name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [ubuntu-18.04, ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt install debhelper valac libgtk-3-dev libgee-0.8-dev libjson-glib-dev libvte-2.91-dev lsb-release dh-make devscripts build-essential
    - name: automatic debuild
      run: debuild -uc -us
